export {default as Home } from '../user/Home'
export {default as Login} from '../user/Login'
export {default as Signup} from '../user/Signup'
export {default as ProductsPage} from '../user/ProductsPage'
export {default as ViewProduct} from '../user/ViewProduct'
export {default as Cart} from '../user/Cart'
export {default as Checkout} from '../user/Checkout'
export {default as Success} from '../user/Success'
export {default as OrderHistory} from '../user/OrderHistory'
export {default as Profile} from '../user/Profile'